name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build github.com/patel8786/ebucks-dealz/cmd/generate-web

    - name: Test
      run: go test github.com/patel8786/ebucks-dealz/cmd/dev-web

    - name: Run
      run: go run github.com/patel8786/ebucks-dealz/cmd/generate-web

