name: GoMan

on:
  workflow_dispatch:
  schedule:
    - cron: '5 0/6 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build github.com/patel8786/ebucks-dealz/cmd/generate-web

    - name: BuildScraper
      run: go build github.com/patel8786/ebucks-dealz/cmd/scraper

    - name: Test
      run: go test github.com/patel8786/ebucks-dealz/cmd/dev-web

    - name: Run
      run: go run github.com/patel8786/ebucks-dealz/cmd/generate-web

    - name: Render static web files
      run: ./generate-web -data-dir ./data -output-dir ./docs2 -path-prefix /ebucks-dealz

    - name: Commit and push any web file changes
      run: |-
        [ -z "$(git status --porcelain=v1 -- docs2 2>/dev/null)" ] && echo "No Changes" && exit 0
        git config user.name "Scraper"
        git config user.email "actions@users.noreply.github.com"
        git add -A docs2
        git commit -m "Latest web"
        git push
